# Generated by Django 4.2.2 on 2023-07-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_language_course_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='language',
            new_name='lang',
        ),
        migrations.RemoveField(
            model_name='language',
            name='language',
        ),
        migrations.AddField(
            model_name='language',
            name='lang',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
