# Generated by Django 4.2.2 on 2023-07-11 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_language_course_lang_remove_language_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='lang',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang',
            new_name='language',
        ),
    ]
